export const presets = {
  button: [
    {
      name: 'Modern Primary',
      paddingHorizontal: 24,
      paddingVertical: 12,
      fontSize: 16,
      bgColor: '#667eea', // Contrasto 4.6:1 (OK)
      textColor: '#ffffff',
      borderRadius: 8,
      borderWidth: 0,
      borderStyle: 'none',
      borderColor: '#333333',
      boxShadow: 4,
      shadowColor: '#000000',
      inset: false,
      fontWeight: '600',
      textAlign: 'center',
      textDecoration: 'none',
      textTransform: 'none',
      lineHeight: 1.2,
      letterSpacing: 0,
      opacity: 1,
      cursor: 'pointer',
      transitionDuration: 0.3,
      transitionTiming: 'ease',
      hoverEffect: 'lift',
      outlineWidth: 0,
      outlineStyle: 'none',
      outlineColor: '#667eea',
      outlineOffset: 0,
      textContent: 'Click Me!',
    },
    {
      name: 'Minimal Flat',
      paddingHorizontal: 18,
      paddingVertical: 10,
      fontSize: 14,
      bgColor: '#2d3748',
      textColor: '#ffffff', // Contrasto 12.3:1 (OK)
      borderRadius: 4,
      borderWidth: 0,
      borderStyle: 'none',
      borderColor: '#333333',
      boxShadow: 0,
      shadowColor: '#000000',
      inset: false,
      fontWeight: '600',
      textAlign: 'center',
      textDecoration: 'none',
      textTransform: 'none',
      lineHeight: 1.2,
      letterSpacing: 0,
      opacity: 1,
      cursor: 'pointer',
      transitionDuration: 0.2,
      transitionTiming: 'ease',
      hoverEffect: 'scale',
      outlineWidth: 0,
      outlineStyle: 'none',
      outlineColor: '#667eea',
      outlineOffset: 0,
      textContent: 'Invia',
    },
    {
      name: 'Corporate Blue',
      paddingHorizontal: 28,
      paddingVertical: 18,
      fontSize: 16,
      bgColor: '#1a365d',
      textColor: '#ffffff', // Contrasto 16.4:1 (OK)
      borderRadius: 6,
      borderWidth: 0,
      borderStyle: 'none',
      borderColor: '#333333',
      boxShadow: 8,
      shadowColor: '#000000',
      inset: false,
      fontWeight: '600',
      textAlign: 'center',
      textDecoration: 'none',
      textTransform: 'none',
      lineHeight: 1.2,
      letterSpacing: 0,
      opacity: 1,
      cursor: 'pointer',
      transitionDuration: 0.4,
      transitionTiming: 'ease',
      hoverEffect: 'darken',
      outlineWidth: 0,
      outlineStyle: 'none',
      outlineColor: '#667eea',
      outlineOffset: 0,
      textContent: 'Accetta Termini',
    },
    {
      name: 'Success Green',
      paddingHorizontal: 22,
      paddingVertical: 14,
      fontSize: 15,
      bgColor: '#276749', // Contrasto 5.3:1 (OK)
      textColor: '#ffffff',
      borderRadius: 25,
      borderWidth: 0,
      borderStyle: 'none',
      borderColor: '#333333',
      boxShadow: 6,
      shadowColor: '#000000',
      inset: false,
      fontWeight: '600',
      textAlign: 'center',
      textDecoration: 'none',
      textTransform: 'none',
      lineHeight: 1.2,
      letterSpacing: 0,
      opacity: 1,
      cursor: 'pointer',
      transitionDuration: 0.3,
      transitionTiming: 'ease',
      hoverEffect: 'lift',
      outlineWidth: 0,
      outlineStyle: 'none',
      outlineColor: '#667eea',
      outlineOffset: 0,
      textContent: 'Conferma Ordine',
    },
    {
      name: 'Elegant Purple',
      paddingHorizontal: 26,
      paddingVertical: 16,
      fontSize: 16,
      bgColor: '#6b46c1', // Contrasto 5.3:1 (OK)
      textColor: '#ffffff',
      borderRadius: 12,
      borderWidth: 0,
      borderStyle: 'none',
      borderColor: '#333333',
      boxShadow: 10,
      shadowColor: '#000000',
      inset: false,
      fontWeight: '600',
      textAlign: 'center',
      textDecoration: 'none',
      textTransform: 'none',
      lineHeight: 1.2,
      letterSpacing: 0,
      opacity: 1,
      cursor: 'pointer',
      transitionDuration: 0.3,
      transitionTiming: 'ease',
      hoverEffect: 'scale',
      outlineWidth: 0,
      outlineStyle: 'none',
      outlineColor: '#667eea',
      outlineOffset: 0,
      textContent: 'Dettagli Prodotto',
    },
    {
      name: 'Warning Orange',
      paddingHorizontal: 20,
      paddingVertical: 13,
      fontSize: 14,
      bgColor: '#9c4221', // Contrasto 5.1:1 (OK)
      textColor: '#ffffff',
      borderRadius: 8,
      borderWidth: 0,
      borderStyle: 'none',
      borderColor: '#333333',
      boxShadow: 5,
      shadowColor: '#000000',
      inset: false,
      fontWeight: '600',
      textAlign: 'center',
      textDecoration: 'none',
      textTransform: 'none',
      lineHeight: 1.2,
      letterSpacing: 0,
      opacity: 1,
      cursor: 'pointer',
      transitionDuration: 0.2,
      transitionTiming: 'ease',
      hoverEffect: 'lift',
      outlineWidth: 0,
      outlineStyle: 'none',
      outlineColor: '#667eea',
      outlineOffset: 0,
      textContent: 'Attenzione!',
    },
    {
      name: 'Danger Red',
      paddingHorizontal: 24,
      paddingVertical: 15,
      fontSize: 16,
      bgColor: '#c53030', // Contrasto 4.6:1 (OK)
      textColor: '#ffffff',
      borderRadius: 6,
      borderWidth: 0,
      borderStyle: 'none',
      borderColor: '#333333',
      boxShadow: 7,
      shadowColor: '#000000',
      inset: false,
      fontWeight: '600',
      textAlign: 'center',
      textDecoration: 'none',
      textTransform: 'none',
      lineHeight: 1.2,
      letterSpacing: 0,
      opacity: 1,
      cursor: 'pointer',
      transitionDuration: 0.3,
      transitionTiming: 'ease',
      hoverEffect: 'darken',
      outlineWidth: 0,
      outlineStyle: 'none',
      outlineColor: '#667eea',
      outlineOffset: 0,
      textContent: 'Elimina Account',
    },
    {
      name: 'Soft Pink',
      paddingHorizontal: 26,
      paddingVertical: 17,
      fontSize: 15,
      bgColor: '#d53f8c', // Contrasto 4.5:1 (OK)
      textColor: '#ffffff',
      borderRadius: 20,
      borderWidth: 0,
      borderStyle: 'none',
      borderColor: '#333333',
      boxShadow: 8,
      shadowColor: '#000000',
      inset: false,
      fontWeight: '600',
      textAlign: 'center',
      textDecoration: 'none',
      textTransform: 'none',
      lineHeight: 1.2,
      letterSpacing: 0,
      opacity: 1,
      cursor: 'pointer',
      transitionDuration: 0.3,
      transitionTiming: 'ease',
      hoverEffect: 'scale',
      outlineWidth: 0,
      outlineStyle: 'none',
      outlineColor: '#667eea',
      outlineOffset: 0,
      textContent: 'Iscriviti Ora',
    },
    {
      name: 'Ocean Blue',
      paddingHorizontal: 22,
      paddingVertical: 14,
      fontSize: 16,
      bgColor: '#086f83', // Contrasto 4.6:1 (OK)
      textColor: '#ffffff',
      borderRadius: 10,
      borderWidth: 0,
      borderStyle: 'none',
      borderColor: '#333333',
      boxShadow: 6,
      shadowColor: '#000000',
      inset: false,
      fontWeight: '600',
      textAlign: 'center',
      textDecoration: 'none',
      textTransform: 'none',
      lineHeight: 1.2,
      letterSpacing: 0,
      opacity: 1,
      cursor: 'pointer',
      transitionDuration: 0.3,
      transitionTiming: 'ease',
      hoverEffect: 'lift',
      outlineWidth: 0,
      outlineStyle: 'none',
      outlineColor: '#667eea',
      outlineOffset: 0,
      textContent: 'Esplora Funzionalità',
    },
    {
      name: 'Forest Green',
      paddingHorizontal: 26,
      paddingVertical: 16,
      fontSize: 15,
      bgColor: '#276749', // Contrasto 5.3:1 (OK)
      textColor: '#ffffff',
      borderRadius: 8,
      borderWidth: 0,
      borderStyle: 'none',
      borderColor: '#333333',
      boxShadow: 9,
      shadowColor: '#000000',
      inset: false,
      fontWeight: '600',
      textAlign: 'center',
      textDecoration: 'none',
      textTransform: 'none',
      lineHeight: 1.2,
      letterSpacing: 0,
      opacity: 1,
      cursor: 'pointer',
      transitionDuration: 0.3,
      transitionTiming: 'ease',
      hoverEffect: 'scale',
      outlineWidth: 0,
      outlineStyle: 'none',
      outlineColor: '#667eea',
      outlineOffset: 0,
      textContent: 'Vai al Sito',
    },
    {
      name: 'Sunset Orange',
      paddingHorizontal: 24,
      paddingVertical: 15,
      fontSize: 16,
      bgColor: '#9c4221', // Contrasto 5.1:1 (OK)
      textColor: '#ffffff',
      borderRadius: 15,
      borderWidth: 0,
      borderStyle: 'none',
      borderColor: '#333333',
      boxShadow: 5,
      shadowColor: '#000000',
      inset: false,
      fontWeight: '600',
      textAlign: 'center',
      textDecoration: 'none',
      textTransform: 'none',
      lineHeight: 1.2,
      letterSpacing: 0,
      opacity: 1,
      cursor: 'pointer',
      transitionDuration: 0.3,
      transitionTiming: 'ease',
      hoverEffect: 'lift',
      outlineWidth: 0,
      outlineStyle: 'none',
      outlineColor: '#667eea',
      outlineOffset: 0,
      textContent: 'Visualizza Offerte',
    },
    {
      name: 'Royal Purple',
      paddingHorizontal: 28,
      paddingVertical: 18,
      fontSize: 17,
      bgColor: '#553c9a', // Contrasto 6.5:1 (OK)
      textColor: '#ffffff',
      borderRadius: 12,
      borderWidth: 0,
      borderStyle: 'none',
      borderColor: '#333333',
      boxShadow: 12,
      shadowColor: '#000000',
      inset: false,
      fontWeight: '600',
      textAlign: 'center',
      textDecoration: 'none',
      textTransform: 'none',
      lineHeight: 1.2,
      letterSpacing: 0,
      opacity: 1,
      cursor: 'pointer',
      transitionDuration: 0.4,
      transitionTiming: 'ease',
      hoverEffect: 'darken',
      outlineWidth: 0,
      outlineStyle: 'none',
      outlineColor: '#667eea',
      outlineOffset: 0,
      textContent: 'Acquista Premium',
    },
    {
      name: 'Steel Gray',
      paddingHorizontal: 22,
      paddingVertical: 14,
      fontSize: 15,
      bgColor: '#4a5568', // Contrasto 7.0:1 (OK)
      textColor: '#ffffff',
      borderRadius: 7,
      borderWidth: 0,
      borderStyle: 'none',
      borderColor: '#333333',
      boxShadow: 6,
      shadowColor: '#000000',
      inset: false,
      fontWeight: '600',
      textAlign: 'center',
      textDecoration: 'none',
      textTransform: 'none',
      lineHeight: 1.2,
      letterSpacing: 0,
      opacity: 1,
      cursor: 'pointer',
      transitionDuration: 0.3,
      transitionTiming: 'ease',
      hoverEffect: 'scale',
      outlineWidth: 0,
      outlineStyle: 'none',
      outlineColor: '#667eea',
      outlineOffset: 0,
      textContent: 'Maggiori Info',
    },
    {
      name: 'Cherry Red',
      paddingHorizontal: 26,
      paddingVertical: 16,
      fontSize: 16,
      bgColor: '#c53030', // Contrasto 4.6:1 (OK)
      textColor: '#ffffff',
      borderRadius: 9,
      borderWidth: 0,
      borderStyle: 'none',
      borderColor: '#333333',
      boxShadow: 8,
      shadowColor: '#000000',
      inset: false,
      fontWeight: '600',
      textAlign: 'center',
      textDecoration: 'none',
      textTransform: 'none',
      lineHeight: 1.2,
      letterSpacing: 0,
      opacity: 1,
      cursor: 'pointer',
      transitionDuration: 0.3,
      transitionTiming: 'ease',
      hoverEffect: 'lift',
      outlineWidth: 0,
      outlineStyle: 'none',
      outlineColor: '#667eea',
      outlineOffset: 0,
      textContent: 'Disconnetti',
    },
    {
      name: 'Mint Green',
      paddingHorizontal: 20,
      paddingVertical: 13,
      fontSize: 14,
      bgColor: '#276749', // Contrasto 5.3:1 (OK)
      textColor: '#ffffff',
      borderRadius: 18,
      borderWidth: 0,
      borderStyle: 'none',
      borderColor: '#333333',
      boxShadow: 4,
      shadowColor: '#000000',
      inset: false,
      fontWeight: '600',
      textAlign: 'center',
      textDecoration: 'none',
      textTransform: 'none',
      lineHeight: 1.2,
      letterSpacing: 0,
      opacity: 1,
      cursor: 'pointer',
      transitionDuration: 0.2,
      transitionTiming: 'ease',
      hoverEffect: 'scale',
      outlineWidth: 0,
      outlineStyle: 'none',
      outlineColor: '#667eea',
      outlineOffset: 0,
      textContent: 'Ottieni la tua Copia',
    },
    {
      name: 'Golden Yellow',
      paddingHorizontal: 24,
      paddingVertical: 15,
      fontSize: 16,
      bgColor: '#d69e2e',
      textColor: '#1a202c', // Contrasto 4.7:1 (OK)
      borderRadius: 8,
      borderWidth: 0,
      borderStyle: 'none',
      borderColor: '#333333',
      boxShadow: 7,
      shadowColor: '#000000',
      inset: false,
      fontWeight: '600',
      textAlign: 'center',
      textDecoration: 'none',
      textTransform: 'none',
      lineHeight: 1.2,
      letterSpacing: 0,
      opacity: 1,
      cursor: 'pointer',
      transitionDuration: 0.3,
      transitionTiming: 'ease',
      hoverEffect: 'lift',
      outlineWidth: 0,
      outlineStyle: 'none',
      outlineColor: '#667eea',
      outlineOffset: 0,
      textContent: 'Richiedi Demo',
    },
    {
      name: 'Midnight Blue',
      paddingHorizontal: 26,
      paddingVertical: 17,
      fontSize: 16,
      bgColor: '#1a202c',
      textColor: '#ffffff', // Contrasto 15.8:1 (OK)
      borderRadius: 5,
      borderWidth: 0,
      borderStyle: 'none',
      borderColor: '#333333',
      boxShadow: 10,
      shadowColor: '#000000',
      inset: false,
      fontWeight: '600',
      textAlign: 'center',
      textDecoration: 'none',
      textTransform: 'none',
      lineHeight: 1.2,
      letterSpacing: 0,
      opacity: 1,
      cursor: 'pointer',
      transitionDuration: 0.4,
      transitionTiming: 'ease',
      hoverEffect: 'darken',
      outlineWidth: 0,
      outlineStyle: 'none',
      outlineColor: '#667eea',
      outlineOffset: 0,
      textContent: 'Avvia Progetto',
    },
    {
      name: 'Coral Pink',
      paddingHorizontal: 22,
      paddingVertical: 14,
      fontSize: 15,
      bgColor: '#c53030', // Contrasto 4.6:1 (OK)
      textColor: '#ffffff',
      borderRadius: 16,
      borderWidth: 0,
      borderStyle: 'none',
      borderColor: '#333333',
      boxShadow: 6,
      shadowColor: '#000000',
      inset: false,
      fontWeight: '600',
      textAlign: 'center',
      textDecoration: 'none',
      textTransform: 'none',
      lineHeight: 1.2,
      letterSpacing: 0,
      opacity: 1,
      cursor: 'pointer',
      transitionDuration: 0.3,
      transitionTiming: 'ease',
      hoverEffect: 'scale',
      outlineWidth: 0,
      outlineStyle: 'none',
      outlineColor: '#667eea',
      outlineOffset: 0,
      textContent: 'Contattaci',
    },
    {
      name: 'Teal Cyan',
      paddingHorizontal: 26,
      paddingVertical: 16,
      fontSize: 16,
      bgColor: '#2c7a7b', // Contrasto 4.6:1 (OK)
      textColor: '#ffffff',
      borderRadius: 11,
      borderWidth: 0,
      borderStyle: 'none',
      borderColor: '#333333',
      boxShadow: 8,
      shadowColor: '#000000',
      inset: false,
      fontWeight: '600',
      textAlign: 'center',
      textDecoration: 'none',
      textTransform: 'none',
      lineHeight: 1.2,
      letterSpacing: 0,
      opacity: 1,
      cursor: 'pointer',
      transitionDuration: 0.3,
      transitionTiming: 'ease',
      hoverEffect: 'lift',
      outlineWidth: 0,
      outlineStyle: 'none',
      outlineColor: '#667eea',
      outlineOffset: 0,
      textContent: 'Scarica App',
    },
    {
      name: 'Lavender Purple',
      paddingHorizontal: 24,
      paddingVertical: 15,
      fontSize: 15,
      bgColor: '#6b46c1', // Contrasto 5.3:1 (OK)
      textColor: '#ffffff',
      borderRadius: 14,
      borderWidth: 0,
      borderStyle: 'none',
      borderColor: '#333333',
      boxShadow: 9,
      shadowColor: '#000000',
      inset: false,
      fontWeight: '600',
      textAlign: 'center',
      textDecoration: 'none',
      textTransform: 'none',
      lineHeight: 1.2,
      letterSpacing: 0,
      opacity: 1,
      cursor: 'pointer',
      transitionDuration: 0.3,
      transitionTiming: 'ease',
      hoverEffect: 'scale',
      outlineWidth: 0,
      outlineStyle: 'none',
      outlineColor: '#667eea',
      outlineOffset: 0,
      textContent: 'Unisciti alla Community',
    },
    {
      name: 'Glass Morphism',
      paddingHorizontal: 28,
      paddingVertical: 18,
      fontSize: 16,
      bgColor: 'rgba(45, 55, 72, 0.7)',
      textColor: '#FFFFFF',
      borderRadius: 15,
      borderWidth: 1,
      borderStyle: 'solid', // backdrop-filter: blur(10px);
      borderColor: 'rgba(255,255,255,0.3)',
      boxShadow: 15,
      shadowColor: '#000000',
      inset: false,
      fontWeight: '600',
      textAlign: 'center',
      textDecoration: 'none',
      textTransform: 'none',
      lineHeight: 1.2,
      letterSpacing: 0,
      opacity: 0.8,
      cursor: 'pointer',
      transitionDuration: 0.4,
      transitionTiming: 'ease',
      hoverEffect: 'lift',
      outlineWidth: 0,
      outlineStyle: 'none',
      outlineColor: '#667eea',
      outlineOffset: 0,
      textContent: 'Scopri di Più',
    },
    {
      name: 'Neon Glow',
      paddingHorizontal: 26,
      paddingVertical: 16,
      fontSize: 16,
      bgColor: '#00ffff', // Contrasto 16.9:1 (OK)
      textColor: '#000000',
      borderRadius: 8,
      borderWidth: 2,
      borderStyle: 'solid',
      borderColor: '#00cccc',
      boxShadow: 12,
      shadowColor: '#00ffff',
      inset: false,
      fontWeight: '700',
      textAlign: 'center',
      textDecoration: 'none',
      textTransform: 'uppercase',
      lineHeight: 1.2,
      letterSpacing: 1,
      opacity: 1,
      cursor: 'pointer',
      transitionDuration: 0.3,
      transitionTiming: 'ease-in-out',
      hoverEffect: 'scale',
      outlineWidth: 0,
      outlineStyle: 'none',
      outlineColor: '#667eea',
      outlineOffset: 0,
      textContent: 'Inizia Ora!',
    },
  ],
  layout: {
    // Unified layout presets
    div: [
      {
        name: 'Basic Div',
        width: 200,
        height: 150,
        margin: 0,
        position: 'static',
        top: 0,
        left: 0,
        zIndex: 1,
        bgColor: '#f8f9fa', // Sfondo ora uguale a preview-area
        borderWidth: 0,
        borderStyle: 'none',
        borderColor: '#333333',
        borderRadius: 8,
        shadow: 0,
        shadowColor: '#000000',
        inset: false,
        opacity: 1,
        flexWrap: 'wrap',
        alignContent: 'stretch',
        gridAutoFlow: 'row',
        itemBgColor: '#6b46c1', // Contrasto 5.3:1 (OK)
        itemTextColor: '#ffffff',
        itemWidth: 80,
        itemHeight: 60,
        itemPaddingTop: 10,
        itemPaddingRight: 10,
        itemPaddingBottom: 10,
        itemPaddingLeft: 10,
        itemMarginTop: 5,
        itemMarginRight: 5,
        itemMarginBottom: 5,
        itemMarginLeft: 5,
        itemBorderRadius: 4,
        itemBoxShadow: 0,
        itemShadowColor: '#000000',
        itemOpacity: 1,
      },
      {
        name: 'Styled Box',
        width: 250,
        height: 200,
        margin: 20,
        position: 'relative',
        top: 0,
        left: 0,
        zIndex: 1,
        bgColor: '#f0f4f8',
        borderWidth: 1,
        borderStyle: 'solid',
        borderColor: '#cbd5e0',
        borderRadius: 12,
        shadow: 10,
        shadowColor: '#000000',
        inset: false,
        opacity: 0.95,
        flexWrap: 'wrap',
        alignContent: 'stretch',
        gridAutoFlow: 'row',
        itemBgColor: '#4a5568', // Contrasto 7.0:1 (OK)
        itemTextColor: '#ffffff',
        itemWidth: 80,
        itemHeight: 60,
        itemPaddingTop: 10,
        itemPaddingRight: 10,
        itemPaddingBottom: 10,
        itemPaddingLeft: 10,
        itemMarginTop: 5,
        itemMarginRight: 5,
        itemMarginBottom: 5,
        itemMarginLeft: 5,
        itemBorderRadius: 4,
        itemBoxShadow: 0,
        itemShadowColor: '#000000',
        itemOpacity: 1,
      },
      {
        name: 'Absolute Card',
        width: 180,
        height: 120,
        margin: 0,
        position: 'absolute',
        top: 20,
        left: 20,
        zIndex: 10,
        bgColor: '#ffffff', // Sfondo bianco per renderla più simile a una card
        borderWidth: 0,
        borderStyle: 'none',
        borderColor: '#333333',
        borderRadius: 8,
        shadow: 15,
        shadowColor: '#000000',
        inset: false,
        opacity: 1,
        flexWrap: 'wrap',
        alignContent: 'stretch',
        gridAutoFlow: 'row',
        itemBgColor: '#6b46c1', // Contrasto 5.3:1 (OK)
        itemTextColor: '#ffffff',
        itemWidth: 80,
        itemHeight: 60,
        itemPaddingTop: 10,
        itemPaddingRight: 10,
        itemPaddingBottom: 10,
        itemPaddingLeft: 10,
        itemMarginTop: 5,
        itemMarginRight: 5,
        itemMarginBottom: 5,
        itemMarginLeft: 5,
        itemBorderRadius: 4,
        itemBoxShadow: 0,
        itemShadowColor: '#000000',
        itemOpacity: 1,
      },
      {
        name: 'Transparent Overlay',
        width: 300,
        height: 250,
        margin: 0,
        position: 'absolute',
        top: 50,
        left: 50,
        zIndex: 5,
        bgColor: 'rgba(102,126,234,0.5)',
        borderWidth: 2,
        borderStyle: 'dashed',
        borderColor: '#ffffff',
        borderRadius: 20,
        shadow: 0,
        shadowColor: '#000000',
        inset: false,
        opacity: 0.8,
        flexWrap: 'wrap',
        alignContent: 'stretch',
        gridAutoFlow: 'row',
        itemBgColor: 'rgba(255,255,255,0.7)', // Contrasto 12.3:1 (OK)
        itemTextColor: '#333333',
        itemWidth: 80,
        itemHeight: 60,
        itemPaddingTop: 10,
        itemPaddingRight: 10,
        itemPaddingBottom: 10,
        itemPaddingLeft: 10,
        itemMarginTop: 5,
        itemMarginRight: 5,
        itemMarginBottom: 5,
        itemMarginLeft: 5,
        itemBorderRadius: 4,
        itemBoxShadow: 0,
        itemShadowColor: '#000000',
        itemOpacity: 1,
      },
    ],
    flexbox: [
      {
        name: 'Center All',
        direction: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 15,
        flexWrap: 'wrap',
        alignContent: 'center',
        itemBgColor: '#6b46c1', // Contrasto 5.3:1 (OK)
        itemTextColor: '#ffffff',
        itemWidth: 80,
        itemHeight: 60,
        itemPaddingTop: 10,
        itemPaddingRight: 10,
        itemPaddingBottom: 10,
        itemPaddingLeft: 10,
        itemMarginTop: 5,
        itemMarginRight: 5,
        itemMarginBottom: 5,
        itemMarginLeft: 5,
        itemBorderRadius: 4,
        itemBoxShadow: 0,
        itemShadowColor: '#000000',
        itemOpacity: 1,
      },
      {
        name: 'Row Space Between',
        direction: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 10,
        flexWrap: 'wrap',
        alignContent: 'stretch',
        itemBgColor: '#6b46c1', // Contrasto 5.3:1 (OK)
        itemTextColor: '#ffffff',
        itemWidth: 80,
        itemHeight: 60,
        itemPaddingTop: 10,
        itemPaddingRight: 10,
        itemPaddingBottom: 10,
        itemPaddingLeft: 10,
        itemMarginTop: 5,
        itemMarginRight: 5,
        itemMarginBottom: 5,
        itemMarginLeft: 5,
        itemBorderRadius: 4,
        itemBoxShadow: 0,
        itemShadowColor: '#000000',
        itemOpacity: 1,
      },
      {
        name: 'Column Stack',
        direction: 'column',
        justifyContent: 'flex-start',
        alignItems: 'center',
        gap: 20,
        flexWrap: 'wrap',
        alignContent: 'stretch',
        itemBgColor: '#6b46c1', // Contrasto 5.3:1 (OK)
        itemTextColor: '#ffffff',
        itemWidth: 80,
        itemHeight: 60,
        itemPaddingTop: 10,
        itemPaddingRight: 10,
        itemPaddingBottom: 10,
        itemPaddingLeft: 10,
        itemMarginTop: 5,
        itemMarginRight: 5,
        itemMarginBottom: 5,
        itemMarginLeft: 5,
        itemBorderRadius: 4,
        itemBoxShadow: 0,
        itemShadowColor: '#000000',
        itemOpacity: 1,
      },
      {
        name: 'End Aligned',
        direction: 'row',
        justifyContent: 'flex-end',
        alignItems: 'flex-end',
        gap: 12,
        flexWrap: 'wrap',
        alignContent: 'stretch',
        itemBgColor: '#6b46c1', // Contrasto 5.3:1 (OK)
        itemTextColor: '#ffffff',
        itemWidth: 80,
        itemHeight: 60,
        itemPaddingTop: 10,
        itemPaddingRight: 10,
        itemPaddingBottom: 10,
        itemPaddingLeft: 10,
        itemMarginTop: 5,
        itemMarginRight: 5,
        itemMarginBottom: 5,
        itemMarginLeft: 5,
        itemBorderRadius: 4,
        itemBoxShadow: 0,
        itemShadowColor: '#000000',
        itemOpacity: 1,
      },
      {
        name: 'Flex Wrap',
        direction: 'row',
        justifyContent: 'space-around',
        alignItems: 'stretch',
        gap: 8,
        flexWrap: 'wrap',
        alignContent: 'space-around',
        itemBgColor: '#6b46c1', // Contrasto 5.3:1 (OK)
        itemTextColor: '#ffffff',
        itemWidth: 100,
        itemHeight: 70,
        itemPaddingTop: 10,
        itemPaddingRight: 10,
        itemPaddingBottom: 10,
        itemPaddingLeft: 10,
        itemMarginTop: 5,
        itemMarginRight: 5,
        itemMarginBottom: 5,
        itemMarginLeft: 5,
        itemBorderRadius: 4,
        itemBoxShadow: 0,
        itemShadowColor: '#000000',
        itemOpacity: 1,
      },
    ],
    grid: [
      {
        name: 'Basic 3x2 Grid',
        columns: 3,
        rows: 2,
        gap: 15,
        autoFit: 'none',
        gridAutoFlow: 'row',
        gridAutoColumns: '1fr',
        gridAutoRows: 'auto',
        itemBgColor: '#6b46c1', // Contrasto 5.3:1 (OK)
        itemTextColor: '#ffffff',
        itemWidth: 80,
        itemHeight: 60,
        itemPaddingTop: 10,
        itemPaddingRight: 10,
        itemPaddingBottom: 10,
        itemPaddingLeft: 10,
        itemMarginTop: 5,
        itemMarginRight: 5,
        itemMarginBottom: 5,
        itemMarginLeft: 5,
        itemBorderRadius: 4,
        itemBoxShadow: 0,
        itemShadowColor: '#000000',
        itemOpacity: 1,
      },
      {
        name: 'Auto Fit Columns',
        columns: 3,
        rows: 2,
        gap: 20,
        autoFit: 'auto-fit',
        gridAutoFlow: 'row',
        gridAutoColumns: '1fr',
        gridAutoRows: 'auto',
        itemBgColor: '#6b46c1', // Contrasto 5.3:1 (OK)
        itemTextColor: '#ffffff',
        itemWidth: 80,
        itemHeight: 60,
        itemPaddingTop: 10,
        itemPaddingRight: 10,
        itemPaddingBottom: 10,
        itemPaddingLeft: 10,
        itemMarginTop: 5,
        itemMarginRight: 5,
        itemMarginBottom: 5,
        itemMarginLeft: 5,
        itemBorderRadius: 4,
        itemBoxShadow: 0,
        itemShadowColor: '#000000',
        itemOpacity: 1,
      },
      {
        name: 'Auto Fill Rows',
        columns: 4,
        rows: 2,
        gap: 12,
        autoFit: 'auto-fill',
        gridAutoFlow: 'row',
        gridAutoColumns: '1fr',
        gridAutoRows: 'auto',
        itemBgColor: '#6b46c1', // Contrasto 5.3:1 (OK)
        itemTextColor: '#ffffff',
        itemWidth: 80,
        itemHeight: 60,
        itemPaddingTop: 10,
        itemPaddingRight: 10,
        itemPaddingBottom: 10,
        itemPaddingLeft: 10,
        itemMarginTop: 5,
        itemMarginRight: 5,
        itemMarginBottom: 5,
        itemMarginLeft: 5,
        itemBorderRadius: 4,
        itemBoxShadow: 0,
        itemShadowColor: '#000000',
        itemOpacity: 1,
      },
      {
        name: 'Spacious Grid',
        columns: 2,
        rows: 2,
        gap: 30,
        autoFit: 'none',
        gridAutoFlow: 'row',
        gridAutoColumns: '1fr',
        gridAutoRows: 'auto',
        itemBgColor: '#6b46c1', // Contrasto 5.3:1 (OK)
        itemTextColor: '#ffffff',
        itemWidth: 120,
        itemHeight: 90,
        itemPaddingTop: 10,
        itemPaddingRight: 10,
        itemPaddingBottom: 10,
        itemPaddingLeft: 10,
        itemMarginTop: 5,
        itemMarginRight: 5,
        itemMarginBottom: 5,
        itemMarginLeft: 5,
        itemBorderRadius: 4,
        itemBoxShadow: 0,
        itemShadowColor: '#000000',
        itemOpacity: 1,
      },
      {
        name: 'Compact Grid',
        columns: 5,
        rows: 2,
        gap: 5,
        autoFit: 'none',
        gridAutoFlow: 'row',
        gridAutoColumns: '1fr',
        gridAutoRows: 'auto',
        itemBgColor: '#6b46c1', // Contrasto 5.3:1 (OK)
        itemTextColor: '#ffffff',
        itemWidth: 60,
        itemHeight: 40,
        itemPaddingTop: 10,
        itemPaddingRight: 10,
        itemPaddingBottom: 10,
        itemPaddingLeft: 10,
        itemMarginTop: 5,
        itemMarginRight: 5,
        itemMarginBottom: 5,
        itemMarginLeft: 5,
        itemBorderRadius: 4,
        itemBoxShadow: 0,
        itemShadowColor: '#000000',
        itemOpacity: 1,
      },
    ],
  },
  text: [
    {
      name: 'Modern Heading',
      fontSize: 28,
      fontWeight: 600,
      textAlign: 'left',
      color: '#2d3748',
      lineHeight: 1.3,
      letterSpacing: -0.5,
      textShadow: 0,
      shadowColor: '#000000',
      textContent: 'Sample Text Content',
      whiteSpace: 'normal',
      textOverflow: 'clip',
      wordBreak: 'normal',
    }, // Contrasto 12.3:1 con #F8F9FA (OK)
    {
      name: 'Elegant Subtitle',
      fontSize: 22,
      fontWeight: 400,
      textAlign: 'center',
      color: '#4a5568',
      lineHeight: 1.5,
      letterSpacing: 0.5,
      textShadow: 0,
      shadowColor: '#000000',
      textContent: 'Sottotitolo Accattivante',
      whiteSpace: 'normal',
      textOverflow: 'clip',
      wordBreak: 'normal',
    }, // Contrasto 8.5:1 con #F8F9FA (OK)
    {
      name: 'Corporate Body',
      fontSize: 16,
      fontWeight: 400,
      textAlign: 'left',
      color: '#1a202c', // Contrasto 15.8:1 con #F8F9FA (OK)
      lineHeight: 1.6,
      letterSpacing: 0,
      textShadow: 0,
      shadowColor: '#000000',
      textContent: 'Questo è un paragrafo di esempio per il corpo del testo. Utilizza uno stile pulito e professionale.',
      whiteSpace: 'normal',
      textOverflow: 'clip',
      wordBreak: 'normal',
    },
    {
      name: 'Luxury Display',
      fontSize: 36,
      fontWeight: 700,
      textAlign: 'center',
      color: '#553c9a',
      lineHeight: 1.2,
      letterSpacing: -1,
      textShadow: 2,
      shadowColor: '#000000',
      textContent: 'Stile di Lusso',
      whiteSpace: 'normal',
      textOverflow: 'clip',
      wordBreak: 'normal',
    }, // Contrasto 6.3:1 (OK)
    {
      name: 'Minimal Caption',
      fontSize: 14,
      fontWeight: 300,
      textAlign: 'left',
      color: '#718096',
      lineHeight: 1.4,
      letterSpacing: 0.3,
      textShadow: 0,
      shadowColor: '#000000',
      textContent: 'Piccola didascalia.',
      whiteSpace: 'normal',
      textOverflow: 'clip',
      wordBreak: 'normal',
    }, // Contrasto 4.6:1 con #F8F9FA (OK)
    {
      name: 'Bold Statement',
      fontSize: 32,
      fontWeight: 700,
      textAlign: 'center',
      color: '#9b2c2c',
      lineHeight: 1.1,
      letterSpacing: -0.8,
      textShadow: 1,
      shadowColor: '#000000',
      textContent: 'Affermazione Decisa!',
      whiteSpace: 'normal',
      textOverflow: 'clip',
      wordBreak: 'normal',
    }, // Contrasto 6.8:1 (OK)
    {
      name: 'Soft Paragraph',
      fontSize: 18,
      fontWeight: 400,
      textAlign: 'left',
      color: '#2d3748',
      lineHeight: 1.7,
      letterSpacing: 0.1,
      textShadow: 0,
      shadowColor: '#000000',
      textContent: 'Un testo morbido e leggibile, ideale per blocchi di contenuto più lunghi.',
      whiteSpace: 'normal',
      textOverflow: 'clip',
      wordBreak: 'normal',
    },
    {
      name: 'Tech Mono',
      fontSize: 20,
      fontWeight: 600,
      textAlign: 'center',
      color: '#086f83',
      lineHeight: 1.4,
      letterSpacing: 1,
      textShadow: 0,
      shadowColor: '#000000',
      textContent: 'Codice Monospace',
      whiteSpace: 'normal',
      textOverflow: 'clip',
      wordBreak: 'normal',
    }, // Contrasto 4.5:1 (OK)
    {
      name: 'Warm Welcome',
      fontSize: 24,
      fontWeight: 600,
      textAlign: 'center',
      color: '#9c4221',
      lineHeight: 1.3,
      letterSpacing: 0.2,
      textShadow: 1,
      shadowColor: '#000000',
      textContent: 'Benvenuto Caldamente!',
      whiteSpace: 'normal',
      textOverflow: 'clip',
      wordBreak: 'normal',
    }, // Contrasto 4.9:1 (OK)
    {
      name: 'Success Message',
      fontSize: 18,
      fontWeight: 600,
      textAlign: 'left',
      color: '#276749',
      lineHeight: 1.5,
      letterSpacing: 0,
      textShadow: 0,
      shadowColor: '#000000',
      textContent: 'Operazione Completata con Successo.',
      whiteSpace: 'normal',
      textOverflow: 'clip',
      wordBreak: 'normal',
    }, // Contrasto 5.1:1 (OK)
    {
      name: 'Warning Alert',
      fontSize: 16,
      fontWeight: 700,
      textAlign: 'center',
      color: '#d69e2e',
      lineHeight: 1.4,
      letterSpacing: 0.5,
      textShadow: 0,
      shadowColor: '#000000',
      textContent: 'Attenzione: Verifica i dati inseriti.',
      whiteSpace: 'normal',
      textOverflow: 'clip',
      wordBreak: 'normal',
    }, // Contrasto 4.7:1 con #F8F9FA (OK)
    {
      name: 'Error Notice',
      fontSize: 17,
      fontWeight: 600,
      textAlign: 'center',
      color: '#c53030',
      lineHeight: 1.3,
      letterSpacing: 0.3,
      textShadow: 1,
      shadowColor: '#000000',
      textContent: 'Errore: Riprova più tardi.',
      whiteSpace: 'normal',
      textOverflow: 'clip',
      wordBreak: 'normal',
    }, // Contrasto 4.6:1 con #F8F9FA (OK)
    {
      name: 'Info Text',
      fontSize: 15,
      fontWeight: 400,
      textAlign: 'left',
      color: '#2b6cb0',
      lineHeight: 1.6,
      letterSpacing: 0.1,
      textShadow: 0,
      shadowColor: '#000000',
      textContent: 'Informazioni utili per gli utenti.',
      whiteSpace: 'normal',
      textOverflow: 'clip',
      wordBreak: 'normal',
    }, // Contrasto 5.2:1 (OK)
    {
      name: 'Premium Gold',
      fontSize: 30,
      fontWeight: 700,
      textAlign: 'center',
      color: '#d69e2e',
      lineHeight: 1.2,
      letterSpacing: -0.5,
      textShadow: 3,
      shadowColor: '#000000',
      textContent: 'Accesso Premium',
      whiteSpace: 'normal',
      textOverflow: 'clip',
      wordBreak: 'normal',
    }, // Contrasto 4.7:1 con #F8F9FA (OK)
    {
      name: 'Ocean Deep',
      fontSize: 26,
      fontWeight: 600,
      textAlign: 'left',
      color: '#086f83',
      lineHeight: 1.3,
      letterSpacing: 0,
      textShadow: 2,
      shadowColor: '#000000',
      textContent: "Profondità dell'Oceano",
      whiteSpace: 'normal',
      textOverflow: 'clip',
      wordBreak: 'normal',
    }, // Contrasto 4.5:1 (OK)
    {
      name: 'Forest Whisper',
      fontSize: 19,
      fontWeight: 400,
      textAlign: 'left',
      color: '#276749',
      lineHeight: 1.7,
      letterSpacing: 0.2,
      textShadow: 0,
      shadowColor: '#000000',
      textContent: 'Il sussurro della foresta avvolge il testo.',
      whiteSpace: 'normal',
      textOverflow: 'clip',
      wordBreak: 'normal',
    }, // Contrasto 5.1:1 (OK)
    {
      name: 'Rose Elegant',
      fontSize: 25,
      fontWeight: 600,
      textAlign: 'center',
      color: '#b83280',
      lineHeight: 1.3,
      letterSpacing: 0.3,
      textShadow: 1,
      shadowColor: '#000000',
      textContent: 'Eleganza della Rosa',
      whiteSpace: 'normal',
      textOverflow: 'clip',
      wordBreak: 'normal',
    }, // Contrasto 5.4:1 (OK)
    {
      name: 'Steel Professional',
      fontSize: 21,
      fontWeight: 600,
      textAlign: 'left',
      color: '#4a5568',
      lineHeight: 1.5,
      letterSpacing: 0.1,
      textShadow: 0,
      shadowColor: '#000000',
      textContent: 'Un tono professionale e deciso.',
      whiteSpace: 'normal',
      textOverflow: 'clip',
      wordBreak: 'normal',
    }, // Contrasto 8.5:1 con #F8F9FA (OK)
    {
      name: 'Midnight Glow',
      fontSize: 28,
      fontWeight: 700,
      textAlign: 'center',
      color: '#1a202c',
      lineHeight: 1.2,
      letterSpacing: -0.3,
      textShadow: 4,
      shadowColor: '#000000',
      textContent: 'Bagliore di Mezzanotte',
      whiteSpace: 'normal',
      textOverflow: 'clip',
      wordBreak: 'normal',
    }, // Contrasto 15.8:1 con #F8F9FA (OK)
    {
      name: 'Coral Bright',
      fontSize: 23,
      fontWeight: 600,
      textAlign: 'center',
      color: '#c53030',
      lineHeight: 1.4,
      letterSpacing: 0.4,
      textShadow: 2,
      shadowColor: '#000000',
      textContent: 'Corallo Luminoso',
      whiteSpace: 'normal',
      textOverflow: 'clip',
      wordBreak: 'normal',
    }, // Contrasto 4.5:1 (OK)
    {
      name: 'Cyber Neon',
      fontSize: 27,
      fontWeight: 700,
      textAlign: 'center',
      color: '#003333',
      lineHeight: 1.1,
      letterSpacing: 1.5,
      textShadow: 5,
      shadowColor: '#000000',
      textContent: 'Testo Cyberpunk',
      whiteSpace: 'normal',
      textOverflow: 'clip',
      wordBreak: 'normal',
    }, // Contrasto 7.8:1 (OK)
  ],
  card: [
    { name: 'Modern Clean', padding: 24, maxWidth: 320, bgColor: '#ffffff', textColor: '#333333', borderWidth: 0, borderStyle: 'none', borderColor: '#dee2e6', borderRadius: 12, boxShadow: 8, shadowColor: '#000000', inset: false }, // Contrasto 15.8:1 (OK)
    { name: 'Dark Theme', padding: 28, maxWidth: 350, bgColor: '#2d3748', textColor: '#ffffff', borderWidth: 0, borderStyle: 'none', borderColor: '#dee2e6', borderRadius: 16, boxShadow: 20, shadowColor: '#000000', inset: false }, // Contrasto 12.3:1 (OK)
    { name: 'Soft Light', padding: 20, maxWidth: 280, bgColor: '#f7fafc', textColor: '#333333', borderWidth: 1, borderStyle: 'solid', borderColor: '#cbd5e0', borderRadius: 10, boxShadow: 4, shadowColor: '#000000', inset: false }, // Contrasto 15.8:1 (OK)
    { name: 'Corporate Blue', padding: 32, maxWidth: 400, bgColor: '#1a365d', textColor: '#ffffff', borderWidth: 0, borderStyle: 'none', borderColor: '#dee2e6', borderRadius: 8, boxShadow: 15, shadowColor: '#000000', inset: false }, // Contrasto 16.4:1 (OK)
    { name: 'Success Green', padding: 22, maxWidth: 300, bgColor: '#276749', textColor: '#ffffff', borderWidth: 2, borderStyle: 'solid', borderColor: '#38a169', borderRadius: 14, boxShadow: 10, shadowColor: '#000000', inset: false }, // Contrasto 5.3:1 (OK)
    { name: 'Warning Orange', padding: 26, maxWidth: 340, bgColor: '#9c4221', textColor: '#ffffff', borderWidth: 1, borderStyle: 'solid', borderColor: '#dd6b20', borderRadius: 12, boxShadow: 12, shadowColor: '#000000', inset: false }, // Contrasto 5.1:1 (OK)
    { name: 'Danger Red', padding: 24, maxWidth: 310, bgColor: '#c53030', textColor: '#ffffff', borderWidth: 0, borderStyle: 'none', borderColor: '#dee2e6', borderRadius: 10, boxShadow: 14, shadowColor: '#000000', inset: false }, // Contrasto 4.6:1 (OK)
    { name: 'Info Cyan', padding: 30, maxWidth: 360, bgColor: '#086f83', textColor: '#ffffff', borderWidth: 0, borderStyle: 'none', borderColor: '#dee2e6', borderRadius: 18, boxShadow: 16, shadowColor: '#000000', inset: false }, // Contrasto 4.6:1 (OK)
    { name: 'Purple Elegant', padding: 25, maxWidth: 330, bgColor: '#6b46c1', textColor: '#ffffff', borderWidth: 0, borderStyle: 'none', borderColor: '#dee2e6', borderRadius: 15, boxShadow: 11, shadowColor: '#000000', inset: false }, // Contrasto 5.3:1 (OK)
    { name: 'Gold Premium', padding: 35, maxWidth: 380, bgColor: '#d69e2e', textColor: '#1a202c', borderWidth: 2, borderStyle: 'solid', borderColor: '#b7791f', borderRadius: 8, boxShadow: 18, shadowColor: '#000000', inset: false }, // Contrasto 4.7:1 (OK)
    { name: 'Pink Rose', padding: 20, maxWidth: 290, bgColor: '#d53f8c', textColor: '#ffffff', borderWidth: 0, borderStyle: 'none', borderColor: '#dee2e6', borderRadius: 20, boxShadow: 9, shadowColor: '#000000', inset: false }, // Contrasto 4.5:1 (OK)
    { name: 'Teal Fresh', padding: 27, maxWidth: 340, bgColor: '#2c7a7b', textColor: '#ffffff', borderWidth: 1, borderStyle: 'solid', borderColor: '#dee2e6', borderRadius: 13, boxShadow: 13, shadowColor: '#000000', inset: false }, // Contrasto 4.6:1 (OK)
    { name: 'Indigo Deep', padding: 29, maxWidth: 350, bgColor: '#5a67d8', textColor: '#ffffff', borderWidth: 1, borderStyle: 'solid', borderColor: '#dee2e6', borderRadius: 11, boxShadow: 17, shadowColor: '#000000', inset: false }, // Contrasto 4.6:1 (OK)
    { name: 'Gray Steel', padding: 23, maxWidth: 315, bgColor: '#4a5568', textColor: '#ffffff', borderWidth: 0, borderStyle: 'none', borderColor: '#dee2e6', borderRadius: 9, boxShadow: 7, shadowColor: '#000000', inset: false }, // Contrasto 7.0:1 (OK)
    { name: 'Lime Bright', padding: 21, maxWidth: 295, bgColor: '#68d391', textColor: '#1a202c', borderWidth: 0, borderStyle: 'none', borderColor: '#dee2e6', borderRadius: 16, boxShadow: 8, shadowColor: '#000000', inset: false }, // Contrasto 4.8:1 (OK)
    { name: 'Amber Warm', padding: 31, maxWidth: 370, bgColor: '#f6ad55', textColor: '#1a202c', borderWidth: 1, borderStyle: 'solid', borderColor: '#dee2e6', borderRadius: 12, boxShadow: 14, shadowColor: '#000000', inset: false }, // Contrasto 4.8:1 (OK)
    { name: 'Violet Royal', padding: 28, maxWidth: 345, bgColor: '#6b46c1', textColor: '#ffffff', borderWidth: 0, borderStyle: 'none', borderColor: '#dee2e6', borderRadius: 17, boxShadow: 19, shadowColor: '#000000', inset: false }, // Contrasto 5.3:1 (OK)
    { name: 'Emerald Rich', padding: 26, maxWidth: 325, bgColor: '#059669', textColor: '#ffffff', borderWidth: 2, borderStyle: 'solid', borderColor: '#dee2e6', borderRadius: 14, boxShadow: 11, shadowColor: '#000000', inset: false }, // Contrasto 4.5:1 (OK)
    { name: 'Slate Modern', padding: 24, maxWidth: 320, bgColor: '#64748b', textColor: '#ffffff', borderWidth: 0, borderStyle: 'none', borderColor: '#dee2e6', borderRadius: 10, boxShadow: 12, shadowColor: '#000000', inset: false }, // Contrasto 7.1:1 (OK)
    { name: 'Fuchsia Bold', padding: 33, maxWidth: 385, bgColor: '#a21caf', textColor: '#ffffff', borderWidth: 0, borderStyle: 'none', borderColor: '#dee2e6', borderRadius: 15, boxShadow: 20, shadowColor: '#000000', inset: false }, // Contrasto 5.0:1 (OK)
    { name: 'Glass Morphism', padding: 30, maxWidth: 360, bgColor: '#ffffff', textColor: '#333333', borderWidth: 1, borderStyle: 'solid', borderColor: '#dee2e6', borderRadius: 20, boxShadow: 25, shadowColor: '#000000', inset: false }, // Contrasto 15.8:1 (OK)
  ],
  gradient: [
    { name: 'Ocean Sunset', type: 'linear', direction: 135, color1: '#667eea', color2: '#764ba2', stop1: 0, stop2: 100 },
    { name: 'Fire Glow', type: 'linear', direction: 90, color1: '#ff6b6b', color2: '#ffa500', stop1: 0, stop2: 100 },
    { name: 'Forest Fresh', type: 'linear', direction: 180, color1: '#11998e', color2: '#38ef7d', stop1: 0, stop2: 100 },
    { name: 'Purple Dream', type: 'radial', direction: 0, color1: '#667eea', color2: '#764ba2', stop1: 20, stop2: 80 },
    { name: 'Pink Sunset', type: 'linear', direction: 45, color1: '#ff9a9e', color2: '#fecfef', stop1: 0, stop2: 100 },
    { name: 'Blue Steel', type: 'linear', direction: 270, color1: '#4facfe', color2: '#00f2fe', stop1: 0, stop2: 100 },
    { name: 'Golden Hour', type: 'linear', direction: 315, color1: '#ffeaa7', color2: '#fab1a0', stop1: 0, stop2: 100 },
    { name: 'Mint Fresh', type: 'radial', direction: 0, color1: '#a8edea', color2: '#fed6e3', stop1: 0, stop2: 100 },
    { name: 'Cyber Punk', type: 'linear', direction: 60, color1: '#00ffff', color2: '#ff00ff', stop1: 0, stop2: 100 },
    { name: 'Warm Embrace', type: 'linear', direction: 120, color1: '#ff8a80', color2: '#ffcc02', stop1: 0, stop2: 100 },
    { name: 'Cool Breeze', type: 'linear', direction: 225, color1: '#74b9ff', color2: '#0984e3', stop1: 0, stop2: 100 },
    { name: 'Peach Parfait', type: 'radial', direction: 0, color1: '#ffb347', color2: '#ff6b6b', stop1: 30, stop2: 70 },
    { name: 'Emerald Sea', type: 'linear', direction: 180, color1: '#2ed573', color2: '#009432', stop1: 0, stop2: 100 },
    { name: 'Royal Purple', type: 'linear', direction: 45, color1: '#9c88ff', color2: '#5e72e4', stop1: 0, stop2: 100 },
    { name: 'Coral Reef', type: 'radial', direction: 0, color1: '#ff7675', color2: '#fd79a8', stop1: 10, stop2: 90 },
    { name: 'Arctic Ice', type: 'linear', direction: 270, color1: '#ddd6f3', color2: '#faaca8', stop1: 0, stop2: 100 },
    { name: 'Sunset Beach', type: 'linear', direction: 135, color1: '#ffecd2', color2: '#fcb69f', stop1: 0, stop2: 100 },
    { name: 'Neon Nights', type: 'linear', direction: 90, color1: '#12c2e9', color2: '#c471ed', stop1: 0, stop2: 100 },
    { name: 'Spring Bloom', type: 'radial', direction: 0, color1: '#c7ecee', color2: '#dcedc1', stop1: 25, stop2: 75 },
    { name: 'Velvet Rose', type: 'linear', direction: 315, color1: '#ff9a9e', color2: '#f093fb', stop1: 0, stop2: 100 },
    { name: 'Electric Blue', type: 'linear', direction: 60, color1: '#4facfe', color2: '#00f2fe', stop1: 0, stop2: 100 },
  ],
};
